language: node_js
node_js:
  - "8"
addons:
  postgresql: "10.5"
env:
  global:
    - PORT=8080
    - PGHOST=127.0.0.1
    - PGPORT=5432
    - PGUSER=travis
    - PGPASSWORD=postgres

services:
  - postgresql

before_install:
  - psql -u travis --password="postgres" < postgres-sql/database.sql

install:
  - npm install
  - npm install -g coveralls

script:
  - ./node_modules/nyc/bin/nyc.js --exclude test --reporter lcovonly npm run test:all
  - coveralls

