sudo: required
language: generic

services:
  - docker

before_script:
  - sudo docker-compose up -d postgres
  - cd shared-server
  - sudo npm install

script:
  - sudo npm run test

after_success:
  - sudo npm run coverage