sudo: required
language: generic

services:
  - docker
  
install:
  - sudo docker-compose build

before_script:
  - sudo docker-compose up -d shared-server postgres
  - sh -c "la -l"
  - sh -c "cd test-server"
  - sh -c "echo $PWD"
  - sh -c "npm install"

script:
  - npm run start-tests

after_success:
  - npm run coverage