sudo: required
language: node_js
node_js:
- '8'

services:
  - docker

before_script:
  - sudo docker-compose up -d postgres
  - cd shared-server
  - npm install

script:
  - npm test

after_success:
  - npm run coverage