language: node_js
node_js:
  - "8"
env:
  global:
    - PORT=8080
    - DB_HOST=127.0.0.1
    - DB_PORT=5432
    - DB_USER=travis
    - DB_PASSWORD=postgres

services:
  - postgres

before_install:
  - postgres -u root -e "SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('postgres')"
  - postgres -u travis --password="postgres" < postgres-sql/database.sql

install:
  - npm install
  - npm install -g coveralls

script:
  - ./node_modules/nyc/bin/nyc.js --exclude test --reporter lcovonly npm run test:all
  - coveralls

