version: "2"
services:
  shared-server:
    volumes:
    - './shared-server/service:/app/service'
    - './shared-server/appServer:/app/appServer'
    - './shared-server/auth:/app/auth'
    - './shared-server/delivery:/app/delivery'
    - './shared-server/payment:/app/payment'
    - './shared-server/tracking:/app/tracking'
    - './shared-server/user:/app/user'
    - './shared-server/others:/app/others'
  postgres:
    volumes:
    - ./postgres-sql/pgdata:/var/lib/postgresql/data
volumes:
    pgdata: {}

