version: "2"
services:
  test-server:
    depends_on:
      - shared-server
      - postgres
    build: ./test-server
    links:
      - shared-server
  shared-server:
    depends_on:
    - postgres
    build: ./shared-server
    ports:
    - "8080:8080"
    container_name: sharedServer_container
    environment:
      - PGPASSWORD=postgres
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
    restart: always
    links:
    - postgres
  postgres:
    build: ./postgres-sql
    container_name: pg_container
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - ./postgres-sql/pgdata:/var/lib/postgresql/data
volumes:
    pgdata: {}